language: java
jdk: oraclejdk8
# To use 7.5GiB memory, specify 'required' for 'sudo'
# https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
sudo: required
dist: trusty
env:
  global:
    # GITHUB_TOKEN
    - secure: "WljmhJOo6S6DoLAUqQ8wXG+6soWQDlJVaamuk5UfT3DWfFjUlD6LkT0pTmvI6jdqbk1k7ogtuLq88VuaaY6OsB/Amz6CbJW/1Z5+EgYKdGY6nN4OSBZ253NGMy0RExP5iZicxCGdtcic7PcouKDpi9WjH0dRqpRkgYEdZGcsL7SlK18dnvmW4I6JGbOOmrOfTWE2nWIVt1Fh53eZiV9bffBHBAQn/di8iEk1hHLrUsDE7UyCw9wchlEW7sDL0rB1KlYvZ/G80y9xDMtGoRQo0EF49s4ACLIyg1uhlLniR0Rx/fHFyjUZLzmmFrlmZdM+AVsmgT/WpctgMW0ixzM3a9Wp9PKEm7KEcpgUpoPQBNYMOuxCe3DKZrHHluey9q7elKew4CamvJCyjbMln0dHJXaavaE/obiSu7YjZfymd9FB+DirjvaiL8ulG8qSzDd4FqvsqNzd18lDmzuGHVDlLYNCox3vlm0kuAM9cckn82f6SakqvMM1ZKSeLhWjD0tbpfd+okBvp2y1LaGGZrUhysEk3MXvxOAMa1pCw7Asj+CI9CAmjKjkykMx7csvjTgmCz9sX1aLqXGtEJnThM8R6OYHA05cr+z2eRsnmMWL/wITUXv8y3qKC42AlaA3M42I0lEVwIDLkL/vAa3nG2EjeqvFJ4kDFO34bOCdGgnBRgk="
    # SONAR_LOGIN
    - secure: "Iqsmknto7LfqqyimLpAd9iAdHGuQN1tJ99hQ/2yNm31g6SxPxBiWEgifZvdJadjsY2YS/YMD6irEsvtgWhL1Meah2Cl8DdPGQTNxz5OOZIYPRwnTsLcE1JcNJbSqgmcWYv6bcaLSJgXDHgRW+C/FwkkEgvXvvWzdxw924vQlUh5h4StCjjOR5u5gFYvTDn4jMXC2TXv9wfh7Kby5DXHGviJk7idtwpl0YcmG/pgdX2RQR2UlNGRFVoDiUse5TmKkPIcIeUICz5I16SeOEEWbM1YbvAaSTMgnHC8t6lej5e7F0McW4IMXKQKPGABnDwc8gxssu3GP/3vbdZn3/JD3DOOSej7mEJhVAkhDOjCQCnyOIuVlSa+BnRwPtKyE7W9JMxMszNmFktFrzJzHVyXfddKEFWjlFMjeccVLFur4fkE8itgZ2uGVNzxMUG35qRIBPkuW4gCDGVmASYheal1KuPupZO7EmnhYQsvwaG8ZM2Ym5eEBMqTneLOsVLzyJeEDDE7Kyi4mzsrJw0ho/QfbNeCZFG9llaU5uQie+ws1TX7T19WjbvmuRB4OpYJylXkdUroPEFqTMMooq7Y+uz+sbnk9GEiPcel/toLJWb878MQO+iEbaEDCaOV2O7IvAFZgL+fFJfLOjXBVA/i1iFmflH7PIIKoeEuqyxfrQzEjcB4="
install:
  # Decrypt settings.xml which is necessary to deploy to Sonatype Maven Repositories
  - if [ -n "$encrypted_6cebf91f1d36_key" ]; then openssl aes-256-cbc -K $encrypted_6cebf91f1d36_key -iv $encrypted_6cebf91f1d36_iv -in .travis/settings.xml.enc -out .travis/settings.xml -d; fi
script:
  - mvn jacoco:prepare-agent verify -B -V
after_success:
  - mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN
deploy:
  - provider: script
    script: mvn deploy --settings .travis/settings.xml
    # Skip cleanup to keep decrepted .travis/settings.xml in workspace
    # https://docs.travis-ci.com/user/deployment/
    skip_cleanup: true
    on:
      branch: develop
