language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: CzkU+4k8O/mnH3EIQLDHNwECheCbBEoGFmo/O4tcjGykxLSXMfXTRtWCYa8a1m8L9fmkfPhiNKbzOwQCIX0LrpPkyU8rYkP14ij6Rqr8IEwJisv6MsfAIewo06Uz51tRwaaDQWZQoRBLUPpAAzSBVML0tUg+3m1b6rQmdKNLbrhD36sTLv2KEwp/KTSIvnUKnLQMVBrq8hV0JENiLrlRI3J14GEvLACc2WHo6xFPDTmUnAz4lqfv2ufmLn0EqophGXqRL3e+imBWEpprR9xoLL2ydC1EqB8vUffvob+jEB3quDwwwBvlSQ1wUq0RE8FzE1FmtCB0hZyW3W/bMz8YVwXTmZr0rj860bSgQl/ntVzod+TGfamkpUhqwE59DY6rKwobZCa4jvFXcPinbE9yhK27CyJHHQ0CTEg3lxuR7fkqaRVPIQDc6QTwSZtWRhSX3yNlaATbokVszmUTp5wm7q4yXbGeqXYj3uuZINnAMghbyOro/ruDC2mfFgOLacKxJk1R0pqlpThLGb6iw6o5qs+PGgLF15YeBGeM56AV2WlIqbxs4WHazBheiHSyOzBNBSEHjIIY4Ptzi22LQAFn0f6oOD0chHRL2mpxaZVjcK/Ylq8DSCvA2YKj7lbY/b0ovwnEd4JfYZ/a21bZUSbV8m/NK5lu4iPYKLkuNEQt0kI=
  - secure: HkAG0zJaSpQlMGu0lum0D7udJqlCVjIP5ZMgAAYH0VUjJ1FSV7iDnUPOfo1daP8Q5pzfi+PsVpKXmGeWQoDF+H47C775aN0RkumvRTZHtF5F5w7uQtwx3mAMLCK7xFmXph7rCmWPldO+GU8nOETxD4CKmgtZHN0Ywv8sU8ZxlK7JMRlLJ/yn9tsRTpKeGLPn4pUgIi1AEy7Rfwlv9NwW6rg43pdXaQtx0iufAgKRH+KbfvRBfgeTiri2XZIUqeOmMMj4BnfNUAQH7381Tiu8TIKLFk3F34Xlp0XPhoRnDK3RbddjHJjI4Paq+pCyP4Vjg8D54S9K/2AELWADOCOWfOXlkj3S9OP0vcw+w4RHTsNxkBrxlQnHxNrl81j8C7//OCMWfw/w0is/Xe7UGo5sU/nBMqG+EaWxfpifqkLuCqfY8iaswDIHQrTpO/tdnHZbn1fblBfseyrW3iIVvQEJUzZlKQclfqGMjgBXjMGUksQ3HqW5gcocG0h6leEe4je8WsZHUzFyOVHd3FiWiB3pelAVZGLYF02gAvRAoQyHblF5zRo5+/PxQy1+zZUBC5LE5/+RO4GroQj8VoVYrtWLawbcLMZ2mAiI5/Yz/V+u+hKpvECI3kFmxmUyVDdgAELEVJUDMgmhLgP/bmezvC98CZmKI5ONKDqkIWMfV1+TGlE=
