networks:
  mqtt-network:
    driver: bridge
services:
  smart-mqtt:
    container_name: smart-mqtt
    hostname: smart-mqtt
    image: smartboot/smart-mqtt:latest
    networks:
      mqtt-network: null
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
#  emqx:
#    container_name: emqx
#    hostname: emqx-mqtt
#    image: emqx/emqx:5.0.3
#    networks:
#      mqtt-network: null
#    restart: always
#    security_opt:
#      - no-new-privileges:true
#    user: root:root
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "100m"
#        max-file: "1"

  smart-mqtt-bench:
    depends_on:
#      - emqx
      - smart-mqtt
    image: smartboot/smart-mqtt-bench:latest
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: root:root
    networks:
      mqtt-network: null
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    command: java -cp smart-mqtt-bench.jar  -Dhost=smart-mqtt -Dconnect=2000 -Dpublisher=2 -Dcount=3 -Dpayload=128 org.smartboot.bench.mqtt.Subscribe
#    command: java -cp smart-mqtt-bench.jar  -Dhost=smart-mqtt -Dconnect=1000 -Dcount=3 -Dpayload=128 org.smartboot.bench.mqtt.Publish
version: '3.7'