spring:
  jpa:
    show-sql: false
    database-platform: com.mindata.blockchain.core.sqlite.config.SQLiteDialect
    generate-ddl: true
sqlite:
  dbName: a.db  #本地sqlite的名字
version: 1
name: ${NAME:maida}
appId: ${APP_ID:wolf}
managerUrl: ${MANAGER_URL:http://192.168.1.86:8888/}