server:
  port: 443
  http-port: 80
  servlet:
    context-path: /qmplatform
  ssl:
    enabled: true
    key-alias: tomcat_https
    key-store: classpath:tomcat_https.keystore
    key-password: 123456
    key-store-password: charon
    key-store-type: JKS
  max-http-header-size: 1024KB

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  profiles:
    active: @spring.profiles.active@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，stat:监控统计、wall：防御sql注入
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/**/*Mapper.xml

# 分页插件
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 加密秘钥
jasypt:
  encryptor:
    password: qcz

jodconverter:
  local:
    enabled: false
    office-home: C:\Program Files (x86)\OpenOffice 4
    max-tasks-per-process: 10
    port-numbers: 8100

# 自定义属性
custom:
  database: qmplatform_single
  packing: @packaging@
