name: Java CI
on: [push, pull_request]

jobs:
  buildOnJava8:
    name: build on java8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          cache: 'maven'
          java-version: 8
      - name: Build with Maven
        run: mvn package
  buildOnJava21:
    name: build on java21
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          cache: 'maven'
          java-version: 21
      - name: Build with Maven
        run: mvn package
